### ISSUE TITLE
Fix Travis build

### ISSUE THREAD

**Issue by Glusk** [Glusk/caesar#67]
Apparently, Travis now only supports free builds for OSS on specific architectures. Add this to `.travis.yml`:
```yaml
os: linux
arch:
  - arm64
  - ppc64le
  - s390x
```

Also, fix Travis build status badge.
